name = "Westar"
license = "MIT"
description = ""
homepage = "http://westar.io/"
tags = []
features = []
min_version = "0.41"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
